#!/usr/bin/env Rscript
#' Manuscript slide deck
#'
#' Assembles a PowerPoint summary of the study from the already-committed
#' manuscript tables (tables/manuscript_table*.csv, tables/*.csv) and figures
#' (figures/figure*.jpeg|png). Unlike analysis/07_manuscript_outputs.R, this
#' script does not recompute the model -- it packages the current committed
#' outputs, so re-run analysis/07_manuscript_outputs.R (and the figure
#' scripts) first if the underlying numbers have changed. The manuscript is
#' blinded for double-anonymized review (see manuscript/manuscript.qmd's
#' header comment); this deck follows the same convention and carries no
#' author/institution names.
#'
#' All on-slide text spells out terms in full (no "endometrial biopsy"/"EMB",
#' "dilation and curettage"/"D&C", "Centers for Medicare & Medicaid
#' Services"/"CMS", etc. abbreviations). Every content slide carries: (1) a
#' small numbered-reference footer naming exactly which manuscript reference
#' numbers its content draws on, and (2) a speaker-notes talking-point
#' script. The reference numbering and full reference list are copied
#' directly from manuscript/manuscript.qmd's numbered References section (as
#' last corrected 2026-09-12 -- see that file's own header comment for the
#' citation-numbering audit history); re-copy `references` below and the
#' per-slide `refs =` numbers if that section is renumbered again.
#'
#' NOTE: the embedded chart images (figures/figure*.jpeg|png) are the
#' manuscript's own published figures, generated by other analysis/ scripts
#' (01-05, 09-10). Their axis labels and legends still use the short strategy
#' names ("EMB", "D&C") baked in at render time; relabeling them in full
#' would mean editing those figure-generation scripts, which was out of
#' scope here since it would change the manuscript's actual published
#' figures, not just this slide deck.
#'
#' Run from the repository root:
#'   Rscript analysis/18_manuscript_slides.R
#'
#' Produces manuscript/manuscript_slides.pptx.

library(samevisit)
library(officer)
library(flextable)
library(magrittr)

fmt_dollar <- function(x, digits = 2) {
  base::paste0("$", base::formatC(base::as.numeric(x), format = "f", digits = digits, big.mark = ","))
}
fmt_pct <- function(x, digits = 1) {
  base::paste0(base::formatC(base::as.numeric(x) * 100, format = "f", digits = digits), "%")
}
format_ref_list <- function(nums) {
  nums <- base::sort(base::unique(base::as.integer(nums)))
  run_id <- base::cumsum(base::c(1L, base::diff(nums) != 1L))
  runs <- base::split(nums, run_id)
  parts <- base::vapply(runs, function(r) {
    if (base::length(r) >= 3L) base::sprintf("%d-%d", r[[1]], r[[base::length(r)]])
    else base::paste(r, collapse = ", ")
  }, character(1))
  base::paste0("References: ", base::paste(parts, collapse = ", "), ".")
}

tables <- "tables"
figs <- "figures"

table3 <- readr::read_csv(base::file.path(tables, "manuscript_table3_strategy_comparison.csv"), show_col_types = FALSE)
table5 <- readr::read_csv(base::file.path(tables, "manuscript_table5_psa_summary.csv"), show_col_types = FALSE)
table6 <- readr::read_csv(base::file.path(tables, "manuscript_table6_thresholds.csv"), show_col_types = FALSE)
table7 <- readr::read_csv(base::file.path(tables, "manuscript_table7_budget_impact.csv"), show_col_types = FALSE)
table8 <- readr::read_csv(base::file.path(tables, "manuscript_table8_evidence_tiers.csv"), show_col_types = FALSE)
table9 <- readr::read_csv(base::file.path(tables, "manuscript_table9_validation_status.csv"), show_col_types = FALSE)
table10 <- readr::read_csv(base::file.path(tables, "manuscript_table10_summary.csv"), show_col_types = FALSE)
geo <- readr::read_csv(base::file.path(tables, "geographic_sensitivity_summary.csv"), show_col_types = FALSE)

combined_row <- table3 %>% dplyr::filter(.data$strategy == "combined_emb")
office_row <- table3 %>% dplyr::filter(.data$strategy == "office_emb")
dnc_row <- table3 %>% dplyr::filter(.data$strategy == "dnc")

psa_cheapest_pct <- table5 %>% dplyr::filter(.data$strategy == "combined_emb") %>% dplyr::pull(.data$pct_draws_cheapest)
threshold_minutes <- table6 %>% dplyr::filter(.data$parameter == "combined_emb_added_minutes") %>% dplyr::pull(.data$threshold_value)
threshold_failure <- table6 %>% dplyr::filter(.data$parameter == "emb_failure_lynch") %>% dplyr::pull(.data$threshold_value)

# ---- flextable styling helper --------------------------------------------

style_ft <- function(ft, font_size = 14) {
  ft %>%
    flextable::fontsize(size = font_size, part = "all") %>%
    flextable::bold(part = "header") %>%
    flextable::bg(bg = "#1F3864", part = "header") %>%
    flextable::color(color = "white", part = "header") %>%
    flextable::autofit()
}

pptx <- officer::read_pptx()

add_notes <- function(pptx, notes) {
  officer::set_notes(pptx, value = notes, location = officer::notes_location_type())
}

add_ref_footer <- function(pptx, refs, top = 7.05) {
  if (base::is.null(refs) || base::length(refs) == 0L) return(pptx)
  txt <- format_ref_list(refs)
  officer::ph_with(
    pptx,
    value = officer::fpar(officer::ftext(txt, prop = officer::fp_text(font.size = 9, italic = TRUE, color = "#595959"))),
    location = officer::ph_location(left = 0.4, top = top, width = 9.2, height = 0.3)
  )
}

add_title_slide <- function(pptx, title, subtitle, notes = NULL) {
  pptx <- officer::add_slide(pptx, layout = "Title Slide", master = "Office Theme")
  pptx <- officer::ph_with(pptx, value = title, location = officer::ph_location_type(type = "ctrTitle"))
  pptx <- officer::ph_with(pptx, value = subtitle, location = officer::ph_location_type(type = "subTitle"))
  if (!base::is.null(notes)) pptx <- add_notes(pptx, notes)
  pptx
}

add_bullets_slide <- function(pptx, title, bullets, font_size = 20, notes = NULL, refs = NULL) {
  pptx <- officer::add_slide(pptx, layout = "Title and Content", master = "Office Theme")
  pptx <- officer::ph_with(pptx, value = title, location = officer::ph_location_type(type = "title"))
  fpar_list <- base::lapply(bullets, function(b) {
    officer::fpar(officer::ftext(b, prop = officer::fp_text(font.size = font_size)))
  })
  block <- base::do.call(officer::block_list, fpar_list)
  pptx <- officer::ph_with(pptx, value = block, location = officer::ph_location_type(type = "body"))
  if (!base::is.null(notes)) pptx <- add_notes(pptx, notes)
  pptx <- add_ref_footer(pptx, refs)
  pptx
}

add_image_slide <- function(pptx, title, image_path, caption = NULL, notes = NULL, refs = NULL) {
  pptx <- officer::add_slide(pptx, layout = "Title Only", master = "Office Theme")
  pptx <- officer::ph_with(pptx, value = title, location = officer::ph_location_type(type = "title"))
  dims <- magick::image_info(magick::image_read(image_path))
  max_w <- 9.0
  max_h <- 4.9
  scale <- base::min(max_w / dims$width, max_h / dims$height)
  w <- dims$width * scale
  h <- dims$height * scale
  left <- (10 - w) / 2
  top <- 1.5
  pptx <- officer::ph_with(
    pptx, value = officer::external_img(image_path, width = w, height = h),
    location = officer::ph_location(left = left, top = top, width = w, height = h)
  )
  if (!base::is.null(caption)) {
    pptx <- officer::ph_with(
      pptx, value = caption,
      location = officer::ph_location(left = 0.5, top = top + h + 0.1, width = 9, height = 0.5)
    )
  }
  if (!base::is.null(notes)) pptx <- add_notes(pptx, notes)
  pptx <- add_ref_footer(pptx, refs)
  pptx
}

add_two_image_slide <- function(pptx, title, image_paths, captions = NULL, notes = NULL, refs = NULL) {
  pptx <- officer::add_slide(pptx, layout = "Title Only", master = "Office Theme")
  pptx <- officer::ph_with(pptx, value = title, location = officer::ph_location_type(type = "title"))
  max_w <- 4.5
  max_h <- 4.3
  lefts <- base::c(0.35, 5.15)
  for (i in base::seq_along(image_paths)) {
    dims <- magick::image_info(magick::image_read(image_paths[[i]]))
    scale <- base::min(max_w / dims$width, max_h / dims$height)
    w <- dims$width * scale
    h <- dims$height * scale
    top <- 1.5
    pptx <- officer::ph_with(
      pptx, value = officer::external_img(image_paths[[i]], width = w, height = h),
      location = officer::ph_location(left = lefts[[i]] + (max_w - w) / 2, top = top, width = w, height = h)
    )
    if (!base::is.null(captions)) {
      pptx <- officer::ph_with(
        pptx, value = captions[[i]],
        location = officer::ph_location(left = lefts[[i]], top = top + max_h + 0.05, width = max_w, height = 0.55)
      )
    }
  }
  if (!base::is.null(notes)) pptx <- add_notes(pptx, notes)
  pptx <- add_ref_footer(pptx, refs)
  pptx
}

add_table_slide <- function(pptx, title, ft, top = 1.5, notes = NULL, refs = NULL) {
  pptx <- officer::add_slide(pptx, layout = "Title Only", master = "Office Theme")
  pptx <- officer::ph_with(pptx, value = title, location = officer::ph_location_type(type = "title"))
  pptx <- officer::ph_with(pptx, value = ft, location = officer::ph_location(left = 0.4, top = top, width = 9.2, height = 5.0))
  if (!base::is.null(notes)) pptx <- add_notes(pptx, notes)
  pptx <- add_ref_footer(pptx, refs)
  pptx
}

# ---- 1. Title --------------------------------------------------------------

pptx <- add_title_slide(
  pptx,
  "Endometrial Biopsy Strategies for Lynch Syndrome Surveillance",
  "A cost-minimization analysis of standalone office biopsy, biopsy combined with colonoscopy, and operative dilation and curettage",
  notes = base::paste(
    "Welcome and introduce the topic: women with Lynch syndrome need regular endometrial cancer surveillance,",
    "and there are three different procedures that can obtain the tissue sample this surveillance requires.",
    "This talk compares what each of those three procedures costs, using a cost-minimization study design.",
    "Note up front that this manuscript is prepared for double-anonymized peer review, so this deck intentionally",
    "carries no author or institution names, matching the manuscript itself."
  )
)

# ---- 2. Objective -----------------------------------------------------------

pptx <- add_bullets_slide(pptx, "Objective", base::c(
  "Women with Lynch syndrome undergo recurring endometrial cancer surveillance, which requires an endometrial tissue sample.",
  base::paste0(
    "Three strategies can obtain that sample: a standalone office endometrial biopsy, an endometrial biopsy performed ",
    "during an already-scheduled surveillance colonoscopy, or operative dilation and curettage."
  ),
  "This cost-minimization analysis asks: assuming equivalent diagnostic adequacy across strategies, which strategy costs the least from a United States health-system and payer perspective?"
), notes = base::paste(
  "Frame the clinical problem before the economics: Lynch syndrome carries a lifetime endometrial cancer risk high",
  "enough that guideline-driven surveillance is standard, and every surveillance visit requires a tissue sample.",
  "Emphasize the key assumption up front, since it is the foundation of the whole study design: we are assuming,",
  "not proving in the base case, that all three ways of getting that sample give equally good diagnostic information.",
  "That assumption is revisited directly in the clinical-outcome sensitivity analysis later in the talk."
), refs = base::c(1, 2, 3, 4))

# ---- 3. Methods overview -----------------------------------------------------

pptx <- add_bullets_slide(pptx, "Methods: Study Design", base::c(
  "Cost-minimization analysis, United States payer perspective, Medicare-anchored allowed amounts (Centers for Medicare & Medicaid Services Physician Fee Schedule; Physician & Other Practitioners by Provider and Service Public Use Files).",
  "All costs reported in 2026 United States dollars; historical costs inflation-adjusted with the Bureau of Labor Statistics Consumer Price Index for Medical Care.",
  "Each strategy modeled as a one-step decision tree: an initial sampling attempt, which either succeeds or escalates to operative dilation and curettage.",
  base::paste0(
    "The biopsy-combined-with-colonoscopy arm was priced under an incremental-cost principle: only costs added on top ",
    "of the already-planned colonoscopy are charged to this arm, since the colonoscopy itself is assumed to happen regardless."
  ),
  "Seventy-seven parameters in the model, each assigned an evidence tier from tier A (Lynch-specific direct data) through tier D (provisional placeholder with no source yet)."
), notes = base::paste(
  "Walk through the decision-tree logic slowly, since it is the mechanical core of the whole model: cost equals the",
  "initial procedure cost, plus the probability of escalation multiplied by the expected cost of the escalation procedure.",
  "Explain the incremental-cost principle carefully -- it is a deliberate and important modeling choice, not an oversight:",
  "because the colonoscopy is already happening for these patients regardless of whether biopsy is added, charging its",
  "full base cost to the combined arm would double-count a cost the patient was already going to incur.",
  "Mention the evidence-tier system briefly here; it gets its own slide shortly."
), refs = base::c(5, 6))

# ---- 4. Model structure -------------------------------------------------------

decision_tree_path <- base::file.path(figs, "figure7_decision_tree.png")
if (base::file.exists(decision_tree_path)) {
  pptx <- add_image_slide(pptx, "Model Structure", decision_tree_path,
                           "Figure: decision-tree structure for each strategy",
                           notes = base::paste(
                             "Point out the shape of each branch: one initial attempt, one possible escalation.",
                             "Note that the figure's own axis and branch labels use the short strategy names baked in",
                             "by the manuscript's figure-generation script; narrate the full names verbally while presenting",
                             "this figure, since the image text itself was not regenerated for this deck.",
                             "Highlight that operative dilation and curettage has no escalation branch of its own in the",
                             "base case -- a simplifying assumption flagged again later in Limitations."
                           ), refs = base::c(7, 8, 9, 10, 11))
}

# ---- 5. Evidence base ---------------------------------------------------------

ft_evidence <- table8 %>%
  dplyr::mutate(
    evidence_tier = base::factor(.data$evidence_tier, levels = base::c("A", "B", "C", "D", "structural")),
    pct_parameters = fmt_pct(.data$pct_parameters / 100)
  ) %>%
  dplyr::arrange(.data$evidence_tier) %>%
  dplyr::rename(`Evidence tier` = evidence_tier, `Number of parameters` = n_parameters, `Percent of parameters` = pct_parameters) %>%
  flextable::flextable() %>%
  style_ft()

pptx <- add_table_slide(
  pptx, "Evidence Base: Parameter Tiers", ft_evidence,
  notes = base::paste(
    "Explain the tier definitions out loud, since the table only shows the letter codes: tier A is Lynch-syndrome-specific",
    "direct data; tier B is contemporary United States public cost or reimbursement data; tier C is general or",
    "adjacent-population published literature; tier D is a provisional placeholder with no source yet identified;",
    "structural means an analysis convention, such as the 2026 reference dollar year, rather than an evidence claim.",
    "Be candid that under eight percent of parameters remain provisional, and that this is disclosed intentionally",
    "rather than hidden. The full source list behind every tier is the References slide, covering the model's",
    "seventy-seven parameters collectively."
  ), refs = base::c(1:19)
)

# ---- 6. Base case results ------------------------------------------------------

fig1_path <- base::file.path(figs, "figure1_strategy_cost_comparison.jpeg")
pptx <- add_image_slide(
  pptx, "Base-Case Results", fig1_path,
  base::sprintf(
    "Biopsy combined with colonoscopy %s versus standalone office biopsy %s versus operative dilation and curettage %s per patient (combined strategy saves %s, or %s, versus office biopsy)",
    fmt_dollar(combined_row$expected_total_cost), fmt_dollar(office_row$expected_total_cost),
    fmt_dollar(dnc_row$expected_total_cost),
    fmt_dollar(office_row$incremental_cost_vs_cheapest), fmt_pct(office_row$pct_difference_vs_cheapest / 100)
  ),
  notes = base::paste(
    "This is the headline result -- give it room to land. Read the three numbers aloud slowly: roughly $485 for",
    "biopsy combined with colonoscopy, roughly $727 for standalone office biopsy, and roughly $3,823 for operative",
    "dilation and curettage. State the comparison both ways: in dollars and as a percentage, since journal style for",
    "this target journal requires both. Note that operative dilation and curettage is not a close third place --",
    "it costs nearly eight times the combined strategy.",
    "As with the model-structure figure, this chart's own legend still uses the short strategy names baked in at",
    "render time; say the full strategy names out loud as you point to each bar."
  ), refs = base::c(2, 3, 4, 5, 6, 7, 10, 11)
)

# ---- 7. Cost drivers ------------------------------------------------------------

pptx <- add_bullets_slide(pptx, "What Drives Each Strategy's Cost", base::c(
  base::paste0(
    "Biopsy combined with colonoscopy: facility-setting professional fee ($60.05), incremental procedure-room time ",
    "($142.55), pathology ($50.75), and a separate preoperative office visit ($88.76) -- no colonoscopy base cost is charged to this arm."
  ),
  "Standalone office biopsy: office visit ($88.76), professional fee ($97.03), pathology ($50.75), plus an escalation-weighted cost contribution from a 13.3 percent initial failure probability.",
  base::paste0(
    "Operative dilation and curettage: dominated by the facility fee ($3,307.24) alone -- its professional fee, pathology, ",
    "preoperative visit, and anesthesia costs already exceed either office-based strategy's total cost before the facility fee is even added."
  )
), notes = base::paste(
  "This slide answers the natural follow-up question: 'why' these numbers, not just 'what' they are.",
  "For the combined arm, emphasize again that the colonoscopy itself is not in this list -- that is deliberate.",
  "For the office arm, note the failure probability is doing real work here: 13.3 percent of patients need a",
  "second attempt, and that risk is priced into the expected cost.",
  "For operative dilation and curettage, make the point vividly: even with a facility fee of zero dollars, this",
  "procedure's other components alone would already cost more than either office-based option's total."
), refs = base::c(2, 3, 4, 5, 6, 7, 10, 11))

# ---- 8. Deterministic sensitivity ------------------------------------------------

fig2_path <- base::file.path(figs, "figure2_tornado.jpeg")
if (base::file.exists(fig2_path)) {
  pptx <- add_image_slide(
    pptx, "One-Way Sensitivity Analysis", fig2_path,
    "The cost difference between the combined strategy and standalone office biopsy is most sensitive to the office biopsy failure probability and the combined strategy's incremental added minutes",
    notes = base::paste(
      "This is a tornado diagram: each bar shows how far the combined-versus-office cost difference moves when one",
      "parameter is varied across its low-to-high range while holding everything else at its base-case value.",
      "The two longest bars are the two parameters that matter most: how often the office biopsy fails on the first",
      "attempt, and how many extra minutes the combined procedure adds to the colonoscopy suite time.",
      "Everything below those two bars matters comparatively little to the conclusion."
    ), refs = base::c(2, 3, 4, 5, 6, 10)
  )
}

# ---- 9. Threshold analysis ---------------------------------------------------------

fig3a_path <- base::file.path(figs, "figure3a_threshold_minutes.jpeg")
fig3b_path <- base::file.path(figs, "figure3b_threshold_office_failure.jpeg")
if (base::file.exists(fig3a_path) && base::file.exists(fig3b_path)) {
  pptx <- add_two_image_slide(
    pptx, "Threshold Analysis", base::list(fig3a_path, fig3b_path),
    base::list(
      base::sprintf("The combined strategy stays the least expensive option below approximately %.1f added minutes (base case: 5 minutes)", threshold_minutes),
      base::sprintf("The combined strategy stays the least expensive option above approximately %.1f percent office biopsy failure (base case: 13.3 percent)", threshold_failure * 100)
    ),
    notes = base::paste(
      "Threshold analysis answers 'how bad would things have to get before the conclusion changes,' rather than",
      "just 'how much does the number move.' Left panel: the combined strategy only stops winning once the extra",
      "procedure-suite time needed for the biopsy climbs past about twelve minutes -- well above the five-minute",
      "base case and even above the twelve-minute upper bound observed in the literature.",
      "Right panel: the combined strategy only stops winning if the office biopsy failure rate drops all the way",
      "down to about seven percent, less than half of the thirteen-point-three percent base-case estimate.",
      "Both thresholds sit comfortably outside the range the evidence actually supports."
    ), refs = base::c(2, 3, 4, 10, 11)
  )
}

# ---- 10. Probabilistic sensitivity analysis -----------------------------------------

fig4_path <- base::file.path(figs, "figure4_psa_incremental_cost.jpeg")
if (base::file.exists(fig4_path)) {
  pptx <- add_image_slide(
    pptx, "Probabilistic Sensitivity Analysis", fig4_path,
    base::sprintf(
      "Across one thousand Monte Carlo simulation draws, the biopsy-combined-with-colonoscopy strategy was the least expensive strategy in %s of draws; operative dilation and curettage was never the least expensive strategy",
      fmt_pct(psa_cheapest_pct / 100)
    ),
    notes = base::paste(
      "Unlike the one-way sensitivity analysis, which moves one parameter at a time, this analysis varies every",
      "uncertain parameter simultaneously across one thousand randomly sampled draws -- each parameter sampled from",
      "a distribution matched to its evidence type, so probabilities and costs and time estimates all vary jointly",
      "the way real-world uncertainty actually behaves.",
      "The headline number to remember: the combined strategy wins in roughly ninety-two percent of those one",
      "thousand simulated scenarios, and operative dilation and curettage never wins in any of them.",
      "The gamma cost distributions themselves are parameterized directly from published shape and rate values",
      "where a source reported them, most notably the historical office-biopsy cost anchor."
    ), refs = base::c(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 18)
  )
}

# ---- 11. Scenario analysis (payer type) -----------------------------------

fig5_path <- base::file.path(figs, "figure5_scenario_comparison.jpeg")
if (base::file.exists(fig5_path)) {
  pptx <- add_image_slide(
    pptx, "Payer Scenario Analysis", fig5_path,
    base::paste0(
      "Medicaid and commercial insurance reimbursement scenarios, scaled by empirical payer-to-Medicare ratios from ",
      "national hospital price-transparency data (Medicaid approximately 0.78 to 0.92 times Medicare; commercial insurance approximately 1.49 to 1.80 times Medicare)"
    ),
    notes = base::paste(
      "The base case is anchored to traditional Medicare, but most patients are not on Medicare, so this scenario",
      "asks whether the conclusion still holds for Medicaid and commercial insurance payment rates.",
      "The scaling ratios themselves are not assumed -- they come from real, published hospital price-transparency",
      "files, comparing what the same hospital was actually paid by each payer type for the same procedure code.",
      "State plainly that the combined strategy remains the least expensive option under both alternative payer",
      "scenarios, not just under Medicare."
    ), refs = base::c(12, 13)
  )
}

# ---- 12. Geographic sensitivity --------------------------------------------------------

fig6_path <- base::file.path(figs, "figure6_geographic_sensitivity.jpeg")
if (base::file.exists(fig6_path)) {
  pptx <- add_image_slide(
    pptx, "Geographic Sensitivity", fig6_path,
    "The biopsy-combined-with-colonoscopy strategy remained the least expensive option at every locality tested; its cost advantage widened, rather than narrowed, in the high-cost locality",
    notes = base::paste(
      "This analysis re-prices all three strategies using real Medicare geographic adjustment factors at four",
      "locations: the national average, Colorado, a low-cost locality in Arkansas, and a high-cost locality in",
      "Manhattan, New York, to test whether the conclusion is just an artifact of using national-average pricing.",
      "The surprising and reassuring finding: the combined strategy's dollar advantage over office biopsy actually",
      "grows in the expensive locality, rather than shrinking -- it is not a fragile, average-pricing-only result."
    ), refs = base::c(5, 6, 13)
  )
}

ft_geo <- geo %>%
  dplyr::select("locality_label", "combined_emb_cost", "office_emb_cost", "dnc_cost", "combined_savings_vs_office") %>%
  dplyr::mutate(dplyr::across(base::c("combined_emb_cost", "office_emb_cost", "dnc_cost", "combined_savings_vs_office"), fmt_dollar)) %>%
  dplyr::rename(
    Locality = locality_label,
    `Biopsy combined with colonoscopy` = combined_emb_cost,
    `Standalone office biopsy` = office_emb_cost,
    `Operative dilation and curettage` = dnc_cost,
    `Combined-strategy savings versus office biopsy` = combined_savings_vs_office
  ) %>%
  flextable::flextable() %>%
  style_ft(font_size = 12)

pptx <- add_table_slide(
  pptx, "Geographic Sensitivity: Cost by Locality", ft_geo,
  notes = base::paste(
    "Use this table as the numeric backup for the geographic figure just shown: read across each row to show that",
    "the combined-strategy savings column is positive, and gets larger, not smaller, moving from Arkansas to",
    "Colorado to Manhattan.",
    "The national row exactly reproduces the base-case numbers shown earlier, which is a useful internal",
    "consistency check to mention -- the geographic adjustment method introduces no distortion at the reference location."
  ), refs = base::c(5, 6, 13)
)

# ---- 13. Budget impact -----------------------------------------------------------------

ft_budget <- table7 %>%
  dplyr::mutate(
    comparator = base::ifelse(.data$comparator == "office_emb", "versus standalone office biopsy", "versus operative dilation and curettage"),
    per_patient_savings = fmt_dollar(.data$per_patient_savings),
    annual_savings = fmt_dollar(.data$annual_savings, digits = 0)
  ) %>%
  dplyr::rename(
    `Patients screened per year` = cohort_size, Comparator = comparator,
    `Per-patient savings` = per_patient_savings, `Annual savings` = annual_savings
  ) %>%
  flextable::flextable() %>%
  style_ft(font_size = 12)

pptx <- add_table_slide(
  pptx, "Budget Impact of Adopting the Combined Strategy", ft_budget,
  notes = base::paste(
    "This translates the per-patient dollar difference into program-level dollars, which is often the number a",
    "hospital system or payer decision-maker actually wants.",
    "Anchor on one illustrative example out loud: at one hundred patients screened per year, switching from",
    "standalone office biopsy to the combined strategy saves roughly twenty-four thousand dollars annually; the",
    "same switch away from operative dilation and curettage saves far more.",
    "Scale this up or down live to match whatever cohort size is relevant to this particular audience's practice.",
    "These savings are arithmetic directly on the base-case per-patient costs shown earlier, so the same sources apply."
  ), refs = base::c(2, 3, 4, 5, 6, 7, 10, 11)
)

# ---- 14. Clinical-outcome sensitivity ---------------------------------------------------

ft_clinical <- table10 %>%
  flextable::flextable() %>%
  style_ft(font_size = 12)

pptx <- add_table_slide(
  pptx, "Clinical-Outcome Sensitivity", ft_clinical, top = 1.5,
  notes = base::paste(
    "This slide directly tests the equal-effectiveness assumption stated back on the Objective slide, rather than",
    "just asserting it.",
    "Adverse events here are driven by how often each strategy ultimately requires operative dilation and",
    "curettage, either as the primary procedure or as a rescue procedure after a failed sampling attempt; since",
    "the combined strategy escalates to dilation and curettage far less often than standalone office biopsy, its",
    "adverse-event exposure is correspondingly much lower.",
    "Be candid about the delayed-neoplasia row: it is reported as exactly zero for both office-based arms under the",
    "current evidence base, which the text is explicit is a null result under current evidence, not a proven true",
    "zero risk -- flag that nuance rather than letting the zero read as definitive."
  ), refs = base::c(7, 8, 9, 10, 14, 15)
)
pptx <- officer::ph_with(
  pptx,
  value = base::paste0(
    "Adverse events are driven by how often a strategy ultimately requires rescue to operative dilation and curettage; ",
    "the combined strategy's lower escalation probability yields substantially lower adverse-event exposure than standalone ",
    "office biopsy. Delayed-neoplasia risk is a null result under current evidence, not a demonstrated finding of zero true risk -- see Limitations."
  ),
  location = officer::ph_location(left = 0.4, top = 5.5, width = 9.2, height = 1.0)
)

# ---- 15. References ---------------------------------------------------------------------

references <- base::c(
  "National Comprehensive Cancer Network. NCCN Clinical Practice Guidelines in Oncology: Genetic/Familial High-Risk Assessment: Colorectal, Endometrial, Esophageal, and Gastric Cancer. Version 1.2026. Accessed September 2, 2026.",
  "Elmasry K, Hurt CN, Sanders D, et al. Strategies for endometrial screening in the Lynch syndrome population: a patient acceptability study. Familial Cancer 2009;8:431-439.",
  "Lecuru F, Le Frere Belda MA, Bats AS, et al. Performance of office hysteroscopy and endometrial biopsy for detecting endometrial disease in women at risk of human non-polyposis colon cancer: a prospective study. International Journal of Gynecological Cancer 2008;18:1326-1331.",
  "Woolderink JM, De Bock GH, Zeeman GG, et al. Feasibility of endometrial sampling by vaginal tampons in women with Lynch syndrome. BMC Women's Health 2020;20:54.",
  "Centers for Medicare & Medicaid Services. Physician Fee Schedule. Accessed August 31, 2026.",
  "Centers for Medicare & Medicaid Services. Hospital Outpatient Prospective Payment System. Accessed August 31, 2026.",
  "Ben-Baruch G, Menczer J, Frenkel Y, Serr DM. Laparoscopy in the management of uterine perforation. Journal of Reproductive Medicine 1982;27:73-76.",
  "Yi Y, Yi Y, Bryce CL, et al. Cost-effectiveness analysis of biopsy strategies for endometrial cancer diagnosis in women with postmenopausal bleeding: Pipelle sampling curette versus dilatation and curettage. Gynecologic Oncology 2018;150:112-118.",
  "Kandil D, Yang X, Stockl T, Liu Y. Clinical outcomes of patients with insufficient sample from endometrial biopsy or curettage. International Journal of Gynecological Pathology 2014;33(5):500-506.",
  "Nebgen DR, Lu KH, Rimes S, Keeler E, Broaddus R, Munsell MF, Lynch PM. Combined colonoscopy and endometrial biopsy cancer screening results in women with Lynch syndrome. Gynecologic Oncology 2014;135:85-89.",
  "Huang M, Sun C, Boyd-Rogers S, et al. Prospective study of combined colon and endometrial cancer screening in women with Lynch syndrome: a patient-centered approach. Journal of Oncology Practice 2011;7:43-47.",
  "Trilliant Health. Hospital Machine-Readable-File Data Directory: consolidated hospital price transparency machine-readable file data (snapshot July 21, 2026). Accessed September 12, 2026.",
  "Medicare Program: Hospital Outpatient Prospective Payment and Ambulatory Surgical Center Payment Systems; Quality Reporting Programs; Overall Hospital Quality Star Rating; Hospital Price Transparency; and Notice of Closure of a Teaching Hospital and Opportunity To Apply for Available Slots. Federal Register 2025;90 (November 25, 2025), document 2025-20907.",
  "Hefler L, Lemach A, Seebacher V, Polterauer S, Tempfer C, Reinthaller A. The intraoperative complication rate of nonobstetric dilation and curettage. Obstetrics & Gynecology 2009;113:1268-1271.",
  "van Hanegem N, Prins MMC, Bongers MY, et al. The accuracy of endometrial sampling in women with postmenopausal bleeding: a systematic review and meta-analysis. European Journal of Obstetrics & Gynecology and Reproductive Biology 2016;197:147-155.",
  "Sakna NA, Elgendi M, Salama MH, Zeinhom A, Labib S, Nabhan AF. Diagnostic accuracy of endometrial sampling tests for detecting endometrial cancer: a systematic review and meta-analysis. BMJ Open 2023;13(6):e072124.",
  "Ray KN, Chari AV, Engberg J, Bertolet M, Mehrotra A. Opportunity costs of ambulatory medical care in the United States. American Journal of Managed Care 2015;21(8):567-574.",
  "Ladabaum U, Wang G, Terdiman J, et al. Strategies to identify the Lynch syndrome among patients with colorectal cancer: a cost-effectiveness analysis. Annals of Internal Medicine 2011;155:69-79.",
  "Munro MG, Kasiewicz JL, Desai VB. Office versus institutional operative hysteroscopy: an economic model. Journal of Minimally Invasive Gynecology 2022;29:535-548."
)

references_notes <- base::paste(
  "This reference list is copied directly from the manuscript's own numbered References section, in the same",
  "citation order, so it stays traceable back to the manuscript rather than drifting from it.",
  "Every earlier content slide's small italic footer names exactly which of these numbered references its claims",
  "draw on; use this slide as the lookup table if asked for a specific source during questions."
)

ref_chunk_size <- 7
ref_chunks <- base::split(base::seq_along(references), base::ceiling(base::seq_along(references) / ref_chunk_size))
for (chunk_i in base::seq_along(ref_chunks)) {
  idx <- ref_chunks[[chunk_i]]
  entries <- base::paste0(idx, ". ", references[idx])
  title <- if (base::length(ref_chunks) > 1) {
    base::sprintf("References (%d of %d)", chunk_i, base::length(ref_chunks))
  } else {
    "References"
  }
  pptx <- add_bullets_slide(pptx, title, entries, font_size = 14,
                             notes = if (chunk_i == 1) references_notes else NULL)
}

# ---- 16. External validation -----------------------------------------------------------

pptx <- add_bullets_slide(pptx, "External Validation", base::c(
  "Ladabaum et al., 2011 (reference 18): used to cross-check this model's own inflation-adjustment methodology, and it reproduced the expected approximately 1.53-times multiplier from 2010 to 2026.",
  base::paste0(
    "Yi et al., 2018 (reference 8): full parameter set extracted, but confirmed structurally incomparable -- their model ",
    "adds diagnostic sensitivity and specificity, disease prevalence, and treatment-effectiveness machinery that this cost-only model does not implement."
  ),
  "Munro et al., 2022 (reference 19): office versus institutional hysteroscopy cost figures retained as reference benchmarks for a structurally different procedure, not independently reproduced by this model."
), notes = base::paste(
  "External validation answers 'does this model's machinery behave sensibly against other published work,' which",
  "is different from, and in addition to, the sensitivity analyses shown earlier.",
  "Be direct that Yi et al. was not numerically reproduced, and explain why that is a deliberate, defensible",
  "decision rather than a missing result: their model answers a different, broader question that includes",
  "diagnostic accuracy and disease prevalence, while this model only answers a cost question."
), refs = base::c(8, 18, 19))

# ---- 17. Limitations --------------------------------------------------------------------

pptx <- add_bullets_slide(pptx, "Limitations", base::c(
  "The cost-minimization design assumes equivalent diagnostic adequacy across strategies; the base case was not extended to a full cost-effectiveness analysis using a quality-adjusted-life-year outcome.",
  "Operative dilation and curettage was modeled as a deterministic reference arm with no escalation branch of its own.",
  "The standalone-office-biopsy repeat-attempt structure rests on a small, non-Lynch-specific evidence base.",
  "Delayed-neoplasia risk is currently a null result for both office-based arms under available evidence, not a demonstrated true-zero risk.",
  "The operative-dilation-and-curettage adverse-event cost is only partially monetized: perforation managed by laparoscopy is included, but laparotomy-involving management and severe hemorrhage are not yet monetized.",
  "Diagnostic sensitivity and specificity inputs come from general-population literature, not Lynch-syndrome-specific studies."
), font_size = 18, notes = base::paste(
  "Present limitations plainly and without hedging -- reviewers and a sophisticated audience will find these",
  "anyway, and presenting them directly builds credibility rather than undermining the result.",
  "The most important one to linger on is the first: this whole study assumes, rather than proves in the base",
  "case, that all three strategies are equally good diagnostically. The clinical-outcome sensitivity slide shown",
  "earlier is the direct attempt to test that assumption rather than merely assert it."
), refs = base::c(7, 9, 14, 16))

# ---- 18. Conclusions ----------------------------------------------------------------------

pptx <- add_bullets_slide(pptx, "Conclusions", base::c(
  base::sprintf(
    "Biopsy combined with colonoscopy cost %s less per patient than standalone office biopsy (%s), and both office-based strategies were far less expensive than operative dilation and curettage (%s).",
    fmt_dollar(office_row$incremental_cost_vs_cheapest), fmt_pct(office_row$pct_difference_vs_cheapest / 100),
    fmt_dollar(dnc_row$expected_total_cost)
  ),
  base::sprintf("The biopsy-combined-with-colonoscopy strategy was the least expensive strategy in %s of one thousand probabilistic simulation draws.", fmt_pct(psa_cheapest_pct / 100)),
  "The cost advantage held across Medicaid and commercial insurance payer scenarios and across all four geographic localities tested, widening rather than narrowing at the high-cost extreme.",
  base::sprintf("The advantage is robust unless the incremental colonoscopy-suite time exceeds approximately %.0f minutes (base case: 5 minutes).", threshold_minutes),
  "Operative dilation and curettage was dominated by both office-based alternatives at every facility fee tested, including a facility fee of zero dollars."
), notes = base::paste(
  "Close by restating the practical, actionable takeaway in plain language: for a Lynch syndrome patient who is",
  "already coming in for a surveillance colonoscopy, adding the endometrial biopsy to that same visit is",
  "consistently the least expensive way to get the tissue sample this surveillance requires, and that conclusion",
  "held up under every stress test applied in this study -- parameter uncertainty, payer type, and geography alike.",
  "Invite questions, and be ready to jump back to the Limitations or Clinical-Outcome-Sensitivity slides if",
  "questions probe the equal-effectiveness assumption."
), refs = base::c(2, 3, 4, 5, 6, 7, 10, 11, 12, 13))

# ---- write ------------------------------------------------------------------------------

out_path <- "manuscript/manuscript_slides.pptx"
base::print(pptx, target = out_path)
base::message("Wrote ", out_path, " (", base::length(pptx), " slides).")
